'use strict';

angular.module('albicillaUserApp')
    .value('PAGE_SIZE', 20)
    .value('PAGE_SIZE_ARY', [20, 50, 100])
    .value('TOP_PAGE', 1000)
    .value('API_SEARCHING_PATH', '/searching/cds')
    .value('API_COMPANY_PATH', '/searching/cds/company')
    .value('API_COMPANIES_RECORDS', '/searching/cds/companies/record')
    .value('API_PARTNER_PATH', '/searching/cds/company/partner')
    .value('DOWNLOAD_PAGE_SIZE', 1000)
    .value('TIMEOUT', 5000)
    .value('DATE_FORMAT', 'yyyy-MM-dd')
    .value('CUSTOMS_DATA_SOURCES', [
        'IMP_EAT', //过境
        'IMP_CMF', //航运
        'IMP_AMERICA',
        'EXP_AMERICA',
        'IMP_COSTARICA',
        'EXP_COSTARICA',
        'IMP_ELSALVADOR',
        'IMP_GUATEMALA',
        'EXP_GUATEMALA',
        'IMP_HONDURAS',
        'IMP_MEXICO',
        'EXP_MEXICO',
        'IMP_MEXICO_SHIPPING',
        'EXP_MEXICO_SHIPPING',
        'IMP_NICARAGUA',
        'IMP_PANAMA',
        'EXP_PANAMA',
        'IMP_ARGENTINA',
        'EXP_ARGENTINA',
        'IMP_BOLIVIA',
        'IMP_BRAZIL',
        'EXP_BRAZIL',
        'IMP_CHILE',
        'EXP_CHILE',
        'IMP_COLOMBIA',
        'EXP_COLOMBIA',
        'IMP_ECUADOR',
        'EXP_ECUADOR',
        'IMP_PARAGUAY',
        'EXP_PARAGUAY',
        'IMP_PERU',
        'EXP_PERU',
        'IMP_URUGUAY',
        'EXP_URUGUAY',
        'IMP_VENEZUELA',
        'EXP_VENEZUELA',
        'IMP_ENGLAND',
        'EXP_ENGLAND',
        'IMP_FRANCE',
        'IMP_GERMANY',
        'IMP_RUSSIA',
        'EXP_RUSSIA',
        'IMP_UKRAINE',
        'EXP_UKRAINE',
        'IMP_INDIA',
        'EXP_INDIA',
        'IMP_JAPAN',
        'IMP_KAZAKHSTAN',
        'EXP_KAZAKHSTAN',
        'IMP_KOREA',
        'IMP_KYRGYZSTAN',
        'IMP_PAKISTAN',
        'IMP_PAKISTAN_SHIPPING',
        'EXP_PAKISTAN_SHIPPING',
        'IMP_PHILIPPINES',
        'EXP_PHILIPPINES',
        'IMP_SRILANKA',
        'EXP_SRILANKA',
        'IMP_TAIWAN',
        'IMP_UZBEKISTAN',
        'EXP_UZBEKISTAN',
        'IMP_VIETNAM',
        'EXP_VIETNAM',
        'IMP_ETHIOPIA',
        'EXP_ETHIOPIA',
        'EXP_TAIWAN',
        'IMP_INDONESIA',
        'EXP_INDONESIA',
        'IMP_UGANDA',
        'EXP_UGANDA',
        'IMP_KENYA',
        'IMP_PANAMA_BL',
        'EXP_PANAMA_BL',
        'IMP_PANAMA_BL_ZLC',
        'EXP_PANAMA_BL_ZLC',
        'IMP_PERU_BL_SEA',
        'EXP_PERU_BL_SEA',
        'IMP_PERU_BL_AIR',
        'EXP_PERU_BL_AIR',
        'IMP_ECUADOR_BL_SEA',
        'EXP_ECUADOR_BL_SEA',
        'IMP_ECUADOR_BL_AIR',
        'EXP_ECUADOR_BL_AIR',
        'IMP_VENEZUELA_BL_SEA',
        'EXP_VENEZUELA_BL_SEA',
        'IMP_VENEZUELA_BL_AIR',
        'EXP_VENEZUELA_BL_AIR',
        'IMP_URUGUAY_BL',
        'EXP_URUGUAY_BL',
        'IMP_VIETNAM_ALL',
        'EXP_VIETNAM_ALL',
        'IMP_NAMIBIA',
        'EXP_NAMIBIA',
        'IMP_LIBERIA',
        'EXP_LIBERIA',
        'IMP_BOTSWANA',
        'EXP_BOTSWANA',
        'IMP_BANGLADESH',
        'EXP_BANGLADESH',
        'IMP_CONGOKINSHASA',
        'EXP_CONGOKINSHASA',
        'IMP_NIGERIA',
        'IMP_CIS',
        'IMP_INDIA_NSW',
        'EXP_INDIA_NSW',
        'IMP_LESOTHO',
        'EXP_LESOTHO',
        'IMP_GSD',
        'IMP_IVOIRE',
        'EXP_IVOIRE',
        'IMP_VIETNAM_APV',
        'EXP_VIETNAM_APV',
        'IMP_MOLDOVA',
        'EXP_MOLDOVA',
        'IMP_TURKEY',
        'EXP_TURKEY'
    ])
    .value('PERMISSION', {
        SHIPMENT_PRO_PERMISSION: 4,
        GLOBAL_PERMISSION: 5,
        GLOBAL_PLUS_PERMISSION: 6,
        GLOBAL_LUXURY_PERMISSION: 7,
        GLOBAL_DELUXE_PERMISSION: 8,
        BRONZE_PERMISSION: 1,
        SILVER_PERMISSION: 2,
        GOLD_PERMISSION: 3,
        TRADE_SO_PERMISSION: 64,
        PARTNER_REPORT_PERMISSION: 16,
        GLOBAL_BUYER_PERMISSION: 32,
        MARKET_ANALYSIS: 128
    })
    .value('ROLE', {
        NORMAL: 0,
        BRONZE: 1,
        SILVER: 2,
        GOLD: 3,
        SHIPMENT_PRO: 4,
        GLOBAL: 5,
        GLOBAL_PLUS: 6,
        GLOBAL_LUXURY: 7,
        GLOBAL_DELUXE: 8
    })
    .value('EXPORT_FILE_PERMISSION', {
        COUNT: {
            role: {
                admin: 1000,
                superuser: 1000,
            },
            member: {
                0: 20,
            },
            default: 1000,
        }
    });